### Creating User
POST http://localhost:3000/api/users/

{
    "username": "Fikri",
    "password" : "nadhira",
    "name": "nadhira raihana"
}


###Get all user
GET http://localhost:3000/api/users/

###Get user by ID
GET http://localhost:3000/api/users/ad793ef5-5857-44f4-aed2-97a6c9fbcc09

###update user name
PATCH http://localhost:3000/api/users/ad793ef5-5857-44f4-aed2-97a6c9fbcc09

{
    "name": "Alfan"
}
