### Creating User
POST http://localhost:3000/api/users/

{
    "username": "Fikri",
    "password" : "nadhira",
    "name": "nadhira raihana"
}


###Get all user
GET http://localhost:3000/api/users/

###Get user by ID
GET http://localhost:3000/api/users/ad793ef5-5857-44f4-aed2-97a6c9fbcc09

###Get all user transaction
GET http://localhost:3000/api/users/transactions/ad793ef5-5857-44f4-aed2-97a6c9fbcc09

###update user name
PATCH http://localhost:3000/api/users/ad793ef5-5857-44f4-aed2-97a6c9fbcc09

{
    "name": "Alfan"
}

### Creating Transactions
POST http://localhost:3000/api/transactions/

{
    "title": "Hadiah ultah",
    "category" : "Gift",
    "createDate": "2024-01-29T14:15:39Z",
    "amount" : "200000",
    "description": "ultah nadhira",
    "paymentType": "bni",
    "user_id": "ad793ef5-5857-44f4-aed2-97a6c9fbcc09"
}

###Get all transaction
GET http://localhost:3000/api/transactions/

###Get transaction by id
GET http://localhost:3000/api/transactions/a194bbd2-3944-43da-9424-e43485bc1bb2

### Delete Transactions
DELETE http://localhost:3000/api/transactions/25e9f96e-208c-4ac6-bfdf-dcec61bcb34e


